primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"

[env]
  DATABASE_URL = "/litefs/simse.db"
  STORAGE_PATH = "/storage"

[[mounts]]
  source = "simse_storage"
  destination = "/storage"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 1200
    soft_limit = 1000

[checks]
  [checks.alive]
    type = "tcp"
    interval = "2s"
    timeout = "2s"
    grace_period = "5s"
