version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - images:/media
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
      CLOUDFLARE_IMAGES_ACCOUNT_ID: ffa300f532eaaec071135605899f7bf8
      PAYLOAD_PUBLIC_CLOUDFLARE_IMAGES_ACCOUNT_HASH: momKfEj2XLFFfTO94YnvIg
      CLOUDFLARE_IMAGES_TOKEN: CctmbG3LzQzRVTtIVPFaMJNBi2C-KR_3yRQgmfIP
      
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  images:
  node_modules:
