build_tag := `git rev-parse --short HEAD`
app_name := "app-cms"
env := env_var_or_default("ENV", "dev")
docker_image := "ghcr.io/simse/simse.io:" + app_name + "-" + build_tag + "-" + env

build:
    cd ../.. && docker build -f apps/app-cms/Dockerfile . -t {{docker_image}} --progress=plain
    docker push {{docker_image}}

deploy:
    ENV=prod DOCKER_IMAGE={{docker_image}} levant deploy nomad.job