service: simon-os

image: simse/os.simse.io

servers:
  web:
    - 116.203.73.52
    - 165.1.76.236

proxy:
  ssl: false 
  host: os.simse.io
  app_port: 4321
  healthcheck:
    path: /

registry:
  server: ghcr.io
  username: simse
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - arm64
    - amd64
  context: "../.."
  cache:
    type: gha
    options: mode=max
    image: kamal-app-build-cache
