# Name of your application. Used to uniquely configure containers.
service: simon-os

# Name of the container image.
image: simse/simon-os

# Deploy to these servers.
servers:
  web:
    - 116.203.73.52
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: os.simse.io
  # Proxy connects to your container on port 80 by default.
  app_port: 4321
  healthcheck:
    path: /

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username: simse

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: arm64
  context: "../.."
  cache:
    type: gha
    options: mode=max
    image: kamal-app-build-cache
