backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
      - { name: category, label: Category }
      - { name: tags, label: Tags, widget: "list" }
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { name: body, label: Body, widget: markdown }
