backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
      - { name: category, label: Category, widget: "select",  options: ["Casual", "Python", "Javascript", "Opinion"] }
      - { name: tags, label: Tags, widget: "list" }
      - { label: "Featured Image", name: "image", widget: "image", required: true }
      - { label: "Type", name: "type", widget: "hidden", default: "blog" }
      - { name: body, label: Body, widget: markdown }
