service: radio-proxy

image: simse/radio-proxy.simse.io

servers:
  web:
    - 116.203.73.52

proxy:
  ssl: false 
  host: radio-proxy.simse.io
  app_port: 3000
  healthcheck:
    path: /up
  buffering:
    responses: false

registry:
  server: ghcr.io
  username: simse
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - arm64
    - amd64
  context: "../.."
  cache:
    type: gha
    options: mode=max
    image: kamal-app-build-cache
