service: simse-io

image: simse/simse.io

servers:
  web: 
    - 116.203.73.52: eu
    - 165.1.76.236: us

proxy:
  ssl: false
  host: simse.io
  app_port: 4321
  healthcheck:
    path: /

registry:
  server: ghcr.io
  username: simse
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - arm64
    - amd64
  cache:
    type: gha
    options: mode=max
    image: kamal-app-build-cache
env:
  clear:
    IMGPROXY_ENDPOINT: https://img.simse.io
  secret:
    - IMGPROXY_SALT
    - IMGPROXY_KEY
  tags:
    eu:
      SERVER_REGION: Europe
    us:
      SERVER_REGION: USA

accessories:
  imgproxy:
    service: imgproxy
    image: ghcr.io/imgproxy/imgproxy:v3.26.1
    hosts:
      - 116.203.73.52
      - 165.1.76.236
    env:
      secret:
        - IMGPROXY_SALT
        - IMGPROXY_KEY
    proxy:
      ssl: false
      host: img.simse.io
      app_port: 8080
      healthcheck:
        path: /health
