name: 'Kamal Deploy'
description: 'Initialises environment for Kamal and runs a deploy'

inputs:
  working-directory:
    required: true
  ssh-key:
    required: true
  infisical-client-id:
    required: true
  infisical-client-secret:
    required: true

runs:
  using: 'composite'
  steps:
  - name: Set up Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 3.2.2
      bundler-cache: true

  - name: Install Kamal
    shell: bash
    run: gem install kamal -v 2.5.3

  - name: Set up Bun
    uses: oven-sh/setup-bun@v2

  - name: Add Bun bin to PATH
    run: echo "export PATH=\$PATH:/usr/local/bin:/home/runner/.bun/bin" >> $GITHUB_ENV

  - name: Install Infisical CLI
    shell: bash
    run: bun install -g @infisical/cli

  - name: Authenticate Infisical CLI
    shell: bash
    run: echo "INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=${{ inputs.infisical-client-id }} --client-secret=${{ inputs.infisical-client-secret }} --silent --plain)" >> "$GITHUB_ENV"

  - uses: webfactory/ssh-agent@v0.7.0
    with:
      ssh-private-key: ${{ inputs.ssh-key }}

  # - name: Set up Docker Buildx
  #   id: buildx
  #   uses: docker/setup-buildx-action@v2

  - name: Expose GitHub Runtime for cache
    uses: crazy-max/ghaction-github-runtime@v3

  - name: Run deploy command
    shell: bash
    run: kamal deploy
    working-directory: ${{ inputs.working-directory }}
