name: Deploy simonOS radio proxy

on:
  push:
    branches:
      - main
    paths:
      - 'packages/radio-proxy/**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Kamal
        uses: ./.github/actions/kamal-deploy
        with:
          working-directory: ./packages/radio-proxy
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          infisical-client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          infisical-client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
