name: Deploy Sanity Studio

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./packages/cms

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Deploy Sanity Studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
        run: bunx sanity deploy --no-browser --token $SANITY_AUTH_TOKEN --project $SANITY_PROJECT_ID --dataset $SANITY_DATASET