name: 'Deploy os.simse.io'
on:
  push:
    branches: [main]
    paths:
      - 'apps/simon-os/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.x
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: apps/simon-os

      - name: Build
        run: pnpm build
        working-directory: apps/simon-os

      - name: Deploy to Cloudflare Pages
        run: pnpm run deploy
        working-directory: apps/simon-os
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
