name: Deploy simse.io
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: depot/setup-action@v1
      - 
        uses: extractions/setup-just@v1
      - 
        uses: superfly/flyctl-actions/setup-flyctl@master
      -
        run: just deploy
        env:
          BRANCH: ${{ github.ref_name }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}