name: Deploy simse.io

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Kamal
        uses: ./.github/actions/kamal-deploy
        with:
          working-directory: ./packages/website
          ssh-key: ${{ secret.SSH_PRIVATE_KEY }}
