name: Deploy simonOS

on:
  push:
    branches:
      - main
    paths:
      - 'packages/simon-os/**'

jobs:
  deploy:
    runs-on: ubuntu-24.04

    env:
      DOCKER_BUILDKIT: 1
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Kamal
        uses: ./.github/actions/kamal-deploy
        with:
          working-directory: ./packages/simon-os
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
