name: 'PR Checks'

on:
  pull_request:

env:
  PEPY_API_KEY: 'bruh'
  SANITY_PROJECT_ID: rjqusm5i
  SANITY_PROJECT_DATASET: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run linting
        run: pnpm lint:check

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Generate Astro types
        run: pnpm astro sync

      - name: Run tsc
        run: pnpm types:check

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Run unit tests
        run: pnpm test

  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      
      - name: Ensure site is building
        run: pnpm build

  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.47.2-jammy
    steps:
      - name: Install unzip
        run: apt-get update && apt-get install -y unzip

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: Run Playwright tests
        run: pnpm playwright test --reporter json
        env:
          PLAYWRIGHT_JSON_OUTPUT_NAME: results.json
          HOME: /root

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: results.json