name: 'PR Checks'

on:
  pull_request:

env:
  PEPY_API_KEY: 'bruh'
  SANITY_PROJECT_ID: rjqusm5i
  SANITY_PROJECT_DATASET: test

defaults:
  run:
    working-directory: ./packages/website

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Run linting
        run: bun run lint

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Generate Astro types
        run: bun run astro sync

      - name: Run tsc
        run: bun run types

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Run unit tests
        run: bun test

  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Ensure site is building
        run: bun run build
