name: 'PR Checks'

on:
  pull_request:

env:
  PEPY_API_KEY: 'bruh'
  SANITY_PROJECT_ID: rjqusm5i
  SANITY_PROJECT_DATASET: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linting
        run: bun run lint:check

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate Astro types
        run: bun run astro sync

      - name: Run tsc
        run: bun run types:check

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run unit tests
        run: bun run test

  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Ensure site is building
        run: bun run build

  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - name: Install unzip
        run: apt-get update && apt-get install -y unzip

      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Playwright tests
        run: bun run playwright test --reporter json
        env:
          PLAYWRIGHT_JSON_OUTPUT_NAME: results.json
          HOME: /root

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: results.json