name: 'PR Checks'

on:
  pull_request:

env:
  PEPY_API_KEY: 'bruh'
  SANITY_PROJECT_ID: rjqusm5i
  SANITY_PROJECT_DATASET: test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Run linting
        run: moon :lint

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Run linting
        run: moon :types

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Run linting
        run: moon :test

  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Run linting
        run: moon :build
