name: test-service-chat
on: 
  push:
    paths:
      - "services/service-chat/**"
      - ".github/workflows/test-service-chat.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        run: npm install -g pnpm
      - 
        name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - 
        uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      -
        run: pnpm install --frozen-lockfile --filter infrastructure
      -
        run: pnpm test
        working-directory: services/service-chat