name: test-service-chat
on: 
  push:
    paths:
      - "services/service-chat/**"
      - ".github/workflows/test-service-chat.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
      - 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        run: npm install -g pnpm
      -
        run: pnpm install --frozen-lockfile --filter infrastructure
      -
        run: pnpm test
        working-directory: services/service-chat